name: Bombardeo TikTok F4F

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Se ejecuta cada 6 horas, puedes cambiarlo

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          sudo apt-get install -y xvfb

      - name: Crear archivo de cookies
        run: |
          echo '${{ secrets.TIKTOK_COOKIES }}' > cookies.json
        # Esto crea un archivo físico que el script sí puede leer

      - name: Ejecutar Bot
        run: xvfb-run python main.py
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.10.20/x64
          TIKTOK_COOKIES: cookies.json
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
